# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Generate_factors <- function(n, dimlimit) {
    .Call(`_Sieve_Generate_factors`, n, dimlimit)
}

psicos <- function(x, j) {
    .Call(`_Sieve_psicos`, x, j)
}

psisin <- function(x, j) {
    .Call(`_Sieve_psisin`, x, j)
}

psipolytri <- function(x, j) {
    .Call(`_Sieve_psipolytri`, x, j)
}

psipoly <- function(x, j) {
    .Call(`_Sieve_psipoly`, x, j)
}

psi <- function(x, j, type) {
    .Call(`_Sieve_psi`, x, j, type)
}

multi_psi <- function(x, index, type) {
    .Call(`_Sieve_multi_psi`, x, index, type)
}

Kernel_M_C <- function(X, type, kernel_para) {
    .Call(`_Sieve_Kernel_M_C`, X, type, kernel_para)
}

Design_M_C <- function(X, basisN, type, index_matrix) {
    .Call(`_Sieve_Design_M_C`, X, basisN, type, index_matrix)
}

least_square_C <- function(Phi, Y) {
    .Call(`_Sieve_least_square_C`, Phi, Y)
}

crossprod_C <- function(Phi, betahat) {
    .Call(`_Sieve_crossprod_C`, Phi, betahat)
}

KRR_cal_beta_C <- function(U, s, lambda, Y) {
    .Call(`_Sieve_KRR_cal_beta_C`, U, s, lambda, Y)
}

KRR_predict_C <- function(trainX, testX, type, beta_hat, kernel_para) {
    .Call(`_Sieve_KRR_predict_C`, trainX, testX, type, beta_hat, kernel_para)
}

